# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6dc687282ef44045e0b6a3a8d6b509dea1335c0b81185b1ec2c6c402409455ddedb17c64db45ed8c1ae009893a3aef3881586b30335cf9a4ac1ddd7fff8afba

test:
  secret_key_base: d6a85ca4ec057cfe487d0c8ff3bd7a52ccac451b55ab261e18b98981d28b6176d8ed0cf3da2cade235b1fe032a26054a198a644382848e4561542d3376ab6108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
